# Generated by Django 5.2.5 on 2025-10-02 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0005_orderitem_color_orderitem_order_no_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nhil', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('getfund_levy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('covid_levy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vat_invoice', to='managementSystem.purchaseorder')),
            ],
        ),
    ]
