# Generated by Django 5.2.5 on 2025-10-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0006_vatinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatinvoice',
            name='total_levy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vatinvoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
