# Generated by Django 5.2.5 on 2025-10-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0008_proformainvoice_proformaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='gross',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='customer_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ProformaItem',
        ),
    ]
