# Generated by Django 5.2.5 on 2025-10-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementSystem', '0009_remove_proformainvoice_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformainvoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='managementSystem.proformainvoice')),
            ],
        ),
    ]
