# Generated by Django 5.2.5 on 2025-08-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_address_worker_email_worker_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('bank', 'Bank Transfer')], max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workers.worker')),
            ],
        ),
    ]
