# Generated by Django 5.2.5 on 2025-08-26 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_workerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('bank', 'Bank Transfer')], default='momo', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
